const fs=require('fs');
const idx=fs.readFileSync('index.html','utf8');
const urb=fs.readFileSync('urbania-dx.html','utf8');
const idxStart=idx.indexOf('<div class="mega-menu-wrap');
const idxEnd=idx.indexOf('</nav>', idxStart);
const urbStart=urb.indexOf('<div class="mega-menu-wrap');
const urbEnd=urb.indexOf('</nav>', urbStart);
console.log('INDEX:');
console.log(idx.substring(idxStart, idxStart+1500));
console.log('--- URBANIA:');
console.log(urb.substring(urbStart, urbStart+1500));
